networks:
  macvlan88:
    driver: macvlan
    driver_opts:
      parent: ens33
    # ❌ อย่าใส่ ipam/subnet/gateway ถ้าใช้ DHCP จาก MikroTik
    # ipam:
    #   config:
    #     - subnet: 192.168.88.0/24
    #       gateway: 192.168.88.1

    volumes:
      - "./apks:/apks"
      - "./downloads:/downloads"
      - "/mnt/avd_ext4/avd:/root/.android/avd"
      - "android_data:/home/androidusr"
      - "android_sdk_cache:/opt/android-sdk"

    healthcheck:
      test: ["CMD", "sh", "-c", "adb devices | grep -q '^emulator-[0-9]\+[[:space:]]*device' && adb shell getprop sys.boot_completed | grep -q 1"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

services:
  emulator:
    build:
      context: ./emulator
      dockerfile: Dockerfile
    container_name: pf_emulator
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN
    networks:
      macvlan88:
        # ❌ ลบ ipv4_address: เพื่อให้ DHCP แจก IP เอง
    shm_size: 2gb

    environment:
      TZ: Asia/Bangkok
      FORCE_DHCP: "1"                     # ✅ เปิด DHCP ใน container
      EMULATOR_DEVICE: emu-33-playstore
      INSTANCE_NAME: pf_emulator
      DEVICE_SERIAL: emulator-5554
      MEMORY: "12288"
      CORES: "4"
      GPU: "swiftshader_indirect"

    volumes:
      - apks:/apks
      - android-keys:/root/.android
      - android_sdk_cache:/opt/android-sdk
      - avd_data_pf_emulator:/root/.android/avd

    healthcheck:
      test: ["CMD", "sh", "-c", "adb devices | grep -q '^${DEVICE_SERIAL}[[:space:]]*device' && adb shell getprop sys.boot_completed | grep -q 1"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

  droidflow:
    build:
      context: ./droidflow
      dockerfile: Dockerfile
    container_name: pf_droidflow
    depends_on:
      emulator:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
    networks:
      macvlan88:
        # ❌ ไม่ต้องกำหนด IP เอง
    environment:
      TZ: Asia/Bangkok
      ADB_SERVER_SOCKET: tcp:pf_emulator:5037
      DEVICE_SERIAL: emulator-5554
      INSTANCE_NAME: pf_emulator
      DROIDFLOW_APPS: >-
        [
          {"label":"KSHOP","pkg":"com.kasikornbank.kpaymerchant"},
          {"label":"LINE","pkg":"jp.naver.line.android"}
        ]
      FORCE_DHCP: "1"                     # ✅ container นี้ก็ขอ DHCP เหมือนกัน

    volumes:
      - apks:/apks
      - android-keys:/root/.android
      - flows:/app/flows

    healthcheck:
      test: ["CMD", "sh", "-c", "adb -H pf_emulator -P 5037 devices | grep -q '^${DEVICE_SERIAL}[[:space:]]*device'"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12
