version: "3.8"

# -------------------------------------------------------------------
# Networks & Volumes declaration
# -------------------------------------------------------------------
networks:
  macvlan88:
    external: true

volumes:
  apks:
  android-keys:
  android_sdk_cache:
  # avd_data:
  avd_data_pf_emulator:
  flows:

# -------------------------------------------------------------------
# Services
# -------------------------------------------------------------------
services:
  emulator:
    build:
      context: ./emulator
      dockerfile: Dockerfile
    container_name: pf_emulator
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    networks:
      - macvlan88
    ports:
      - "5037:5037"   # ADB
      - "5900:5900"   # VNC
      - "6080:6080"   # noVNC (web)

    environment:
      # เวลาโซน
      TZ: Asia/Bangkok
      # ขอ IP โดย DHCP ทุกครั้งที่สตาร์ท
      FORCE_DHCP: "1"
      # ชื่อ AVD ที่จะสร้าง / เรียกใช้
      EMULATOR_DEVICE: emu-33-playstore
      # RAM, CPU cores, GPU backend
      MEMORY: "6144"
      CORES: "4"
      GPU: "swiftshader_indirect"

    volumes:
      # ตำแหน่งเก็บ APK, license และ cache SDK
      - apks:/apks
      - android-keys:/root/.android
      - android_sdk_cache:/opt/android-sdk
      # - avd_data:/root/.android/avd
      - avd_data_pf_emulator:/root/.android/avd

    healthcheck:
      # test: ["CMD", "sh", "-c", "adb devices | grep -q emulator-5555.*device"]
      test: ["CMD", "sh", "-c", "adb devices | grep -q '^emulator-5554[[:space:]]*device' && adb shell getprop sys.boot_completed | grep -q 1"]
      start_period: 180s     # ← wait 3 minutes before starting retries
      interval: 15s
      timeout: 10s
      retries: 12            # ← allow up to ~30 minutes of retries if needed

  droidflow:
    build:
      context: ./droidflow
      dockerfile: Dockerfile
    container_name: pf_droidflow
    depends_on:
      emulator:
        condition: service_healthy
    networks:
      - macvlan88
    ports:
      - "5001:5000"

    environment:
      # เวลาโซน
      TZ: Asia/Bangkok
      # ตั้งค่า ADB
      # ให้เชื่อมไปยัง ADB server ของ emulator container แทน localhost
      ADB_SERVER_SOCKET: tcp:pf_emulator:5037
      DEVICE_SERIAL: emulator-5554
      INSTANCE_NAME: pf_emulator
      # แอปที่จะสั่ง automate
      DROIDFLOW_APPS: >-
        [
          {"label":"KSHOP","pkg":"com.kasikornbank.kpaymerchant"},
          {"label":"LINE","pkg":"jp.naver.line.android"}
        ]

    # ← ย้าย volumes มาระดับเดียวกับ environment/ports
    volumes:
      - apks:/apks
      - android-keys:/root/.android
      - flows:/app/flows

    healthcheck:
      # ใช้ same syntax กับ emulator แล้ว grep ให้ตรงกับ 5555
      # test: ["CMD", "sh", "-c", "adb -H pf_emulator -P 5037 devices | grep -q emulator-5555.*device"]
      test: ["CMD", "sh", "-c", "adb -H pf_emulator -P 5037 devices | grep -q '^emulator-5554[[:space:]]*device'"]
      start_period: 180s     # ← wait 3 minutes before starting retries
      interval: 15s
      timeout: 10s
      retries: 12            # ← allow up to ~30 minutes of retries if needed
