networks:
  macvlan88:
    external: true
    # driver: macvlan
    # driver_opts:
    #   parent: ens33
  backend:
    driver: bridge
    # If you truly use DHCP from MikroTik, don't add ipam/subnet/gateway here.
    # ipam:
    #   config:
    #     - subnet: 192.168.88.0/24
    #       gateway: 192.168.88.1

volumes:
  apks:
  android-keys:
  android_sdk_cache:
  avd_data_pf_emulator:
  flows:

services:
  emulator:
    build:
      context: ./emulator
      dockerfile: Dockerfile
    container_name: pf_emulator
    restart: unless-stopped
    privileged: true
    devices: ["/dev/kvm:/dev/kvm"]
    cap_add: ["NET_ADMIN"]
    shm_size: 2gb
    # networks: ["macvlan88"]
    networks: ["macvlan88", "backend"]
    environment:
      TZ: Asia/Bangkok
      FORCE_DHCP: "1"
      EMULATOR_DEVICE: emu-33-playstore
      INSTANCE_NAME: pf_emulator
      DEVICE_SERIAL: emulator-5554
      MEMORY: "12288"
      CORES: "4"
      GPU: "swiftshader_indirect"
    volumes:
      - apks:/apks
      - android-keys:/root/.android
      - android_sdk_cache:/opt/android-sdk
      - avd_data_pf_emulator:/root/.android/avd
    healthcheck:
      test: ["CMD", "sh", "-c", "adb devices | grep -q \"^$$DEVICE_SERIAL[[:space:]]*device\" && adb -s $$DEVICE_SERIAL shell getprop sys.boot_completed | grep -q 1"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

  droidflow:
    build:
      context: ./droidflow
      dockerfile: Dockerfile
    container_name: pf_droidflow
    depends_on:
      emulator:
        condition: service_healthy
    cap_add: ["NET_ADMIN"]
    # networks: ["macvlan88"]
    # networks: ["macvlan88", "backend"]
    networks: ["backend"]
    environment:
      TZ: Asia/Bangkok
      ADB_SERVER_SOCKET: tcp:pf_emulator:5037
      DEVICE_SERIAL: emulator-5554
      INSTANCE_NAME: pf_emulator
      DROIDFLOW_APPS: >-
        [
          {"label":"KSHOP","pkg":"com.kasikornbank.kpaymerchant"},
          {"label":"LINE","pkg":"jp.naver.line.android"}
        ]
      # FORCE_DHCP: "1"
    volumes:
      - apks:/apks
      - android-keys:/root/.android
      - flows:/app/flows
    healthcheck:
      test: ["CMD", "sh", "-c", "adb -H pf_emulator -P 5037 devices | grep -q \"^$$DEVICE_SERIAL[[:space:]]*device\""]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12
