version: "3.8"

networks:
  macvlan88:
    external: true

volumes:
  apks:
  android-keys:
  android_sdk_cache:
  avd_data:
  flows:

services:
  emulator:
    build:
      context: ./emulator
      dockerfile: Dockerfile
    container_name: pf_emulator
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    networks:
      - macvlan88
    environment:
      FORCE_DHCP: "1"
      TZ: Asia/Bangkok
      EMULATOR_DEVICE: emu-33-playstore
      MEMORY: "6144"
      CORES: "4"
      GPU: "swiftshader_indirect"
    volumes:
      - apks:/apks
      - android-keys:/root/.android
      - android_sdk_cache:/opt/android-sdk
      - avd_data:/root/.android/avd
    healthcheck:
      test: ["CMD-SHELL", "adb devices | grep -q emulator-5554.*device"]
      interval: 15s
      timeout: 10s
      retries: 5

  droidflow:
    build:
      context: ./droidflow
      dockerfile: Dockerfile
    container_name: pf_droidflow
    depends_on:
      emulator:
        condition: service_healthy
    network_mode: service:emulator
    ports:
      - "5001:5000"
    environment:
      ADB_SERVER_SOCKET: tcp:127.0.0.1:5037
      DEVICE_SERIAL: emulator-5555
      INSTANCE_NAME: pf_emulator
      DROIDFLOW_APPS: >-
        [
          {"label":"KSHOP","pkg":"com.kasikornbank.kpaymerchant"},
          {"label":"LINE","pkg":"jp.naver.line.android"}
        ]
      TZ: Asia/Bangkok
    volumes:
      - apks:/apks
      - flows:/app/flows
      - android-keys:/root/.android
    healthcheck:
      test: ["CMD-SHELL", "adb -H 127.0.0.1 -P 5037 devices | grep -q emulator-5555"]
      interval: 15s
      timeout: 10s
      retries: 5