networks:
  backend:
    driver: bridge

volumes:
  apks:
  android-keys:
  android_sdk_cache:
  avd_data_pf_emulator:
  flows:

services:
  emulator:
    build:
      context: ./emulator
      dockerfile: Dockerfile
    container_name: pf_emulator
    restart: unless-stopped
    privileged: true
    devices: ["/dev/kvm:/dev/kvm"]
    cap_add: ["NET_ADMIN"]
    shm_size: 2gb
    networks: ["backend"]
    ports:
      - "6080:6080"
      - "5900:5900"
      # - "5037:5037"
    environment:
      TZ: Asia/Bangkok
      EMULATOR_DEVICE: emu-33-playstore
      INSTANCE_NAME: pf_emulator
      DEVICE_SERIAL: emulator-5554
      MEMORY: "12288"
      CORES: "4"
      GPU: "swiftshader_indirect"
    volumes:
      - apks:/apks
      - android-keys:/root/.android
      - android_sdk_cache:/opt/android-sdk
      - avd_data_pf_emulator:/root/.android/avd
    healthcheck:
      test: ["CMD", "sh", "-c", "adb devices | grep -q \"^$$DEVICE_SERIAL[[:space:]]*device\" && adb -s $$DEVICE_SERIAL shell getprop sys.boot_completed | grep -q 1"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

  droidflow:
    build:
      context: ./droidflow
      dockerfile: Dockerfile
    container_name: pf_droidflow
    depends_on:
      emulator:
        condition: service_healthy
    cap_add: ["NET_ADMIN"]
    networks: ["backend"]
    ports:
      - "5000:5000"
    environment:
      TZ: Asia/Bangkok
      ADB_SERVER_SOCKET: tcp:pf_emulator:5037
      DEVICE_SERIAL: emulator-5554
      # ADB_SERVER_SOCKET: tcp:pf_emulator:5037
      # ANDROID_ADB_SERVER_HOST: pf_emulator
      # ANDROID_ADB_SERVER_PORT: "5037"
      # DEVICE_SERIAL: emulator-5554
      INSTANCE_NAME: pf_emulator
      DROIDFLOW_APPS: >-
        [
          {"label":"KSHOP","pkg":"com.kasikornbank.kpaymerchant"},
          {"label":"LINE","pkg":"jp.naver.line.android"}
        ]
    volumes:
      - apks:/apks
      - android-keys:/root/.android
      - flows:/app/flows
    healthcheck:
      # test: ["CMD", "sh", "-c", "adb -H pf_emulator -P 5037 devices | grep -q \"^$$DEVICE_SERIAL[[:space:]]*device\""]
      # test: ["CMD", "sh", "-c", "adb devices | grep -q \"^$$DEVICE_SERIAL[[:space:]]*device\""]
      # test: ["CMD","sh","-lc","adb connect pf_emulator:5555 >/dev/null 2>&1 || true; adb devices | grep -Eq '^emulator-[0-9]+[[:space:]]+device$'"]
      test: ["CMD", "sh", "-c", "adb -H pf_emulator -P 5037 devices | grep -Eq '^emulator-[0-9]+[[:space:]]+device$'"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12